name: 'backup-repo-to-gitee'
description: '同步 GitHub 仓库到 Gitee 仓库'
inputs:
  giteerepo:
    description: 'Gitee 仓库，例如 REPO，默认和github用户名一样。'
    required: false
  giteeuser:
    description: 'Gitee 用户名，默认和github用户名一样。'
    required: false
  giteetoken:
    description: 'Gitee token'
    required: true
  token:
    description: 'GitHub 令牌，用于私有仓库的拉取。'
    default: ${{ github.token }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.giteerepo }}
    - ${{ inputs.giteeuser }}
    - ${{ inputs.giteetoken }}
