name: 'sync-gitee-mirror-vt'
description: '同步 GitHub 仓库到 Gitee 仓库'
inputs:
  repository:
    description: 'Gitee 仓库，例如 abersheeran/gitee-mirror'
    required: true
  username:
    description: 'Gitee 用户名，默认和github用户名一样。'
    required: false
  password:
    description: 'Gitee 密码，用于登录。'
    required: true
  token:
    description: 'GitHub 令牌，用于私有仓库的拉取。'
    default: ${{ github.token }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repository }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    